// web/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { api, setMemberToken } from '@/api'
import type { MemberInfo } from '@/types'
import { Coffee } from 'lucide-vue-next'

const router = useRouter()
const phone = ref('')
const code = ref('')
const error = ref('')
const loading = ref(false)

async function handleLogin() {
  if (!phone.value || !/^1\d{10}$/.test(phone.value)) {
    error.value = '请输入正确的手机号'
    return
  }
  if (!code.value) {
    error.value = '请输入验证码'
    return
  }
  loading.value = true
  error.value = ''
  try {
    const data = await api.post<{ token: string; member: MemberInfo }>('/member/login', {
      phone: phone.value,
      code: code.value,
    })
    setMemberToken(data.token)
    router.push('/member')
  } catch (e: any) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="login-page">
    <div class="login-card">
      <div class="login-header">
        <div class="login-logo">
          <Coffee :size="32" />
        </div>
        <h1>会员登录</h1>
        <p>手机号 + 验证码登录</p>
      </div>

      <form @submit.prevent="handleLogin" class="login-form">
        <div v-if="error" class="login-error">{{ error }}</div>
        <div class="form-group">
          <label>手机号</label>
          <input
            v-model="phone"
            type="tel"
            placeholder="请输入手机号"
            maxlength="11"
          />
        </div>
        <div class="form-group">
          <label>验证码</label>
          <div class="code-row">
            <input
              v-model="code"
              type="text"
              placeholder="请输入验证码"
              maxlength="6"
            />
            <span class="code-hint">固定验证码：123456</span>
          </div>
        </div>
        <button type="submit" class="login-btn" :disabled="loading">
          {{ loading ? '登录中...' : '登 录' }}
        </button>
      </form>
    </div>
  </div>
</template>

<style scoped>
.login-page {
  min-height: calc(100vh - 64px);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
}

.login-card {
  width: 100%;
  max-width: 400px;
  background: var(--brand-surface);
  border-radius: var(--radius-lg);
  border: 1px solid var(--brand-border);
  padding: 40px 32px;
  box-shadow: var(--shadow-md);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.login-logo {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: var(--brand-primary);
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 16px;
}

.login-header h1 {
  font-family: var(--font-serif);
  font-size: 1.5rem;
  font-weight: 700;
  margin-bottom: 8px;
}

.login-header p {
  font-size: 0.9rem;
  color: var(--brand-text-light);
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.login-error {
  background: #FFEBEE;
  color: #C62828;
  font-size: 0.85rem;
  padding: 10px 14px;
  border-radius: var(--radius-sm);
}

.form-group label {
  display: block;
  font-size: 0.9rem;
  font-weight: 500;
  margin-bottom: 6px;
}

.form-group input {
  width: 100%;
  padding: 12px 14px;
  border: 1.5px solid var(--brand-border);
  border-radius: var(--radius-md);
  font-size: 1rem;
  transition: border-color 0.2s;
}

.form-group input:focus {
  outline: none;
  border-color: var(--brand-primary);
}

.code-row {
  display: flex;
  gap: 12px;
  align-items: center;
}

.code-row input {
  flex: 1;
}

.code-hint {
  font-size: 0.75rem;
  color: var(--brand-text-light);
  white-space: nowrap;
}

.login-btn {
  width: 100%;
  padding: 14px;
  background: var(--brand-primary);
  color: white;
  border-radius: var(--radius-md);
  font-size: 1rem;
  font-weight: 600;
  transition: background 0.2s;
}

.login-btn:hover:not(:disabled) {
  background: var(--brand-primary-dark);
}

.login-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>

// admin/src/pages/LoginPage.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../App'
import { Coffee } from 'lucide-react'

export function LoginPage() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const { login } = useAuth()
  const navigate = useNavigate()

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!username || !password) {
      setError('请输入用户名和密码')
      return
    }
    setLoading(true)
    setError('')
    try {
      const res = await fetch('/api/admin/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      })
      const json = await res.json()
      if (json.code !== 0) {
        setError(json.message || '登录失败')
        return
      }
      login(json.data.admin, json.data.token)
      navigate('/dashboard')
    } catch {
      setError('网络错误，请稍后重试')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-muted/50">
      <div className="w-full max-w-sm bg-card rounded-xl shadow-sm border border-border p-8">
        <div className="flex flex-col items-center mb-6">
          <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mb-3">
            <Coffee className="text-primary" size={24} />
          </div>
          <h1 className="text-xl font-bold">山野咖啡后台</h1>
          <p className="text-sm text-muted-foreground mt-1">请登录以继续</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {error && (
            <div className="bg-destructive/10 text-destructive text-sm px-3 py-2 rounded-md">
              {error}
            </div>
          )}
          <div>
            <label className="text-sm font-medium block mb-1">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              placeholder="请输入用户名"
              autoComplete="username"
            />
          </div>
          <div>
            <label className="text-sm font-medium block mb-1">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              placeholder="请输入密码"
              autoComplete="current-password"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full bg-primary text-primary-foreground py-2 rounded-md text-sm font-medium hover:bg-primary/90 disabled:opacity-50 transition-colors"
          >
            {loading ? '登录中...' : '登 录'}
          </button>
        </form>
      </div>
    </div>
  )
}
